<?xml version="1.0" encoding="UTF-8"?>

<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://eccomerce.com/categoria"
        xmlns:tns="http://eccomerce.com/categoria"
        elementFormDefault="qualified">

    <xs:element name="obtenerCategoriaRequest">
        <xs:complexType>
            <xs:sequence>

                <xs:element
                        name="id"
                        type="xs:long"/>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="obtenerCategoriaResponse">
        <xs:complexType>
            <xs:sequence>

                <xs:element
                        name="id"
                        type="xs:long"/>

                <xs:element
                        name="nombre"
                        type="xs:string"/>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>