<?xml version="1.0" encoding="UTF-8"?>

<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://eccomerce.com/producto"
        xmlns:tns="http://eccomerce.com/producto"
        elementFormDefault="qualified">

    <xs:element name="obtenerProductoRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id"
                            type="xs:long"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="obtenerProductoResponse">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="id"
                            type="xs:long"/>

                <xs:element name="nombre"
                            type="xs:string"/>

                <xs:element name="descripcion"
                            type="xs:string"/>

                <xs:element name="precio"
                            type="xs:double"/>

                <xs:element name="stock"
                            type="xs:int"/>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>